modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]] #mandatory
modId="universalores"
displayName="Universal Ores"
logoFile="examplemod.png" #optional
credits="Inspration from the ATMTeam who created atm modpacks for minecraft"
authors="Theo Morris"
description='''My first mod description'''


[[dependencies.examplemod]]  
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
